# Generated by Django 6.1 on 2026-08-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_contact_number',
            field=models.CharField(blank=True, help_text='Optional school contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='school_quote',
            field=models.CharField(blank=True, help_text='Optional school quote or motto', max_length=300),
        ),
    ]
