# Generated by Django 6.1 on 2026-09-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0004_student_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive assignments are excluded from invoice generation without deleting the record.')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='fees.feecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'fee_category')},
            },
        ),
    ]
