# Generated by Django 6.1 on 2026-08-15 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='e.g. "Grade 5", "Nursery"', max_length=50)),
                ('section', models.CharField(blank=True, help_text='e.g. "A", "B"', max_length=10)),
                ('teacher', models.ForeignKey(blank=True, help_text='The class (homeroom) teacher, if assigned.', limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('class_name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Class-Subject Mapping',
                'verbose_name_plural': 'Class-Subject Mappings',
                'unique_together': {('class_obj', 'subject')},
            },
        ),
    ]
