# Generated by Django 6.1 on 2026-08-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='', help_text='Short code for quick reference, e.g. "MATH", "ENG", "SCI"', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
