# Generated by Django 6.1 on 2026-08-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'First Term'), (2, 'Second Term'), (3, 'Third Term'), (4, 'Fourth Term'), (5, 'Final (Aggregate)')])),
                ('academic_year', models.CharField(help_text='e.g. "2025-2026"', max_length=9)),
                ('is_final', models.BooleanField(default=False, help_text='True only for the computed aggregate exam, never set manually for real terms.')),
            ],
            options={
                'unique_together': {('term', 'academic_year')},
            },
        ),
    ]
