# Generated by Django 6.1 on 2026-08-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit_hour',
            field=models.DecimalField(decimal_places=1, default=4.0, help_text='Credit hours for this subject, e.g. 4.0', max_digits=3),
        ),
    ]
