# Generated by Django 6.1 on 2026-08-15 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, help_text="The Student's date of birth.", null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text="The Student's gender.", max_length=10, null=True)),
                ('parent_name', models.CharField(blank=True, help_text="The name of the Student's parent or guardian.", max_length=100, null=True)),
                ('parent_contact', models.CharField(blank=True, help_text="The contact number of the Student's parent or guardian.", max_length=15, null=True)),
                ('photo_url', models.URLField(blank=True, help_text="URL to the Student's photo.", null=True)),
                ('user', models.OneToOneField(help_text='The Login account this Student profile is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
