# Generated by Django 6.1 on 2026-08-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text="The Student's photo, uploaded from device.", null=True, upload_to='student_photos/'),
        ),
    ]
