# Generated by Django 6.1 on 2026-08-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, help_text="Class roll number, e.g. '14'", max_length=20),
        ),
    ]
