# Generated by Django 6.1 on 2026-08-15 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, help_text="The Teacher's academic qualification.", max_length=200, null=True)),
                ('contact', models.CharField(blank=True, help_text="The Teacher's contact number.", max_length=15, null=True)),
                ('subject', models.CharField(blank=True, help_text='The subject the Teacher primarily teaches.', max_length=100, null=True)),
                ('user', models.OneToOneField(help_text='The login account this Teacher profile is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
