# Generated by Django 6.1 on 2026-08-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subject_credit_hour'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='The subject(s) this Teacher teaches.', related_name='teachers', to='academics.subject'),
        ),
    ]
